### ISSUE TITLE
model trained on more data throws error during prediction

### ISSUE THREAD

**Issue by wwerkk** [wwerkk/MC-FP#16]
A model trained on dataset segmented with a small ``hop_length`` parameter (resulting in a much higher number of frames) does not work for prediction: 
```----------------------------------------
Prompt:  []
Generating sequence...
Temperature:
 0.0
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62437)
Traceback (most recent call last):
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/site-packages/pythonosc/osc_server.py", line 33, in handle
    server.dispatcher.call_handlers_for_packet(self.request[0], self.client_address)
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/site-packages/pythonosc/dispatcher.py", line 193, in call_handlers_for_packet
    handler.invoke(client_address, timed_msg.message)
  File "/Users/wwerkowicz/miniconda/envs/cpu/lib/python3.10/site-packages/pythonosc/dispatcher.py", line 54, in invoke
    self.callback(message.address, self.args, *message)
  File "/Users/wwerkowicz/GS/MC/MC-FP/MC-FP-master/generate.py", line 126, in handle_g
    seq = generate(sequence_length=sequence_length, temperature=temperature, prompt=prompt)
  File "/Users/wwerkowicz/GS/MC/MC-FP/MC-FP-master/generate.py", line 97, in generate
    p_label = sample(preds[0], temperature)
  File "/Users/wwerkowicz/GS/MC/MC-FP/MC-FP-master/generate.py", line 71, in sample
    probas = np.random.multinomial(1, preds, 1)
  File "mtrand.pyx", line 4272, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 391, in numpy.random._common.check_array_constraint
  File "_common.pyx", line 377, in numpy.random._common._check_array_cons_bounded_0_1
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs
----------------------------------------```

**Comment by wwerkk** [comment]
turns out it was caused by ``temperature`` passed into ``sample`` function - it cannot be equal zero so it's been capped at 0.001 as of https://github.com/wwerkk/MC-FP/commit/4b3c40d4519dd3fce570a351d06cc0f44cde14d1
